services:
  app:
    build:
      dockerfile: .docker/php/Dockerfile
      context: .
      args:
        PHP_VERSION: 8.3
    working_dir: /app
    restart: "no"
    user: "1000:1000"
    volumes:
      - .:/app
    environment:
      COMPOSER_MEMORY_LIMIT: 2G
      COMPOSER_ALLOW_SUPERUSER: 0
